#!/bin/bash

# to run this on startup put the path to this script into /home/pi/.config/lxsession/LXDE-pi/autostart
# syntax: @/home/pi/rockberry/startup


ROOT_DIR=$(dirname "$0")

# Kill runnning rockberry processes
"$ROOT_DIR/shutdown"

# JACK
chrt 80 "$ROOT_DIR/jack2/build/linux/jackd" -R -P 80 -d alsa -P hw:CODEC -C hw:CODEC -p 256 -n 3 &
sleep 5

# QJackCtl
qjackctl &

# Sooperlooper
chrt 70 sooperlooper -L "$ROOT_DIR/settings/sooperlooper.slsess" &

# Set default multicast device to wlan0 
# (otherwise GUI updates would be sent over eth0)
sudo route add -net 224.0.0.0 netmask 240.0.0.0 wlan0

# GUI Backend
"$ROOT_DIR/mobmuplat-gui/rockberry-backend.py" &

